---
- name: Register container image
  hosts: docker
  become: true
  vars_files:
    /etc/ansible/vars.yml

  tasks:
    - name: Log into registry
      docker_login:
        username: "{{ hub_user }}"
        password: "{{ hub_pass }}"
        registry_url: "https://hub.docker.com/repository/docker/asimpson25/pluralsight-course"
      register: login

    - name: show login information
      debug:
        var: login
