---
- name: Automate docker-compose.yml deployment using the docker_compose module
  hosts: docker
  become: yes

  tasks:
    # - name: Tear down existing services
    #   docker_compose:
    #     project_src: wordpress
    #     state: absent

    - name: Create and start services
      docker_compose:
        project_src: wordpress
      register: output

    - debug:
        var: output

    # - name: Run 'docker-compose up' again
    #   docker_compose:
    #     project_src: wordpress
